// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: appsinstalled.proto

package appsinstalled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserApps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []uint32               `protobuf:"varint,1,rep,name=apps" json:"apps,omitempty"`
	Lat           *float64               `protobuf:"fixed64,2,opt,name=lat" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,3,opt,name=lon" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserApps) Reset() {
	*x = UserApps{}
	mi := &file_appsinstalled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserApps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserApps) ProtoMessage() {}

func (x *UserApps) ProtoReflect() protoreflect.Message {
	mi := &file_appsinstalled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserApps.ProtoReflect.Descriptor instead.
func (*UserApps) Descriptor() ([]byte, []int) {
	return file_appsinstalled_proto_rawDescGZIP(), []int{0}
}

func (x *UserApps) GetApps() []uint32 {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *UserApps) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *UserApps) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

var File_appsinstalled_proto protoreflect.FileDescriptor

const file_appsinstalled_proto_rawDesc = "" +
	"\n" +
	"\x13appsinstalled.proto\"B\n" +
	"\bUserApps\x12\x12\n" +
	"\x04apps\x18\x01 \x03(\rR\x04apps\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lonB\x11Z\x0f./appsinstalled"

var (
	file_appsinstalled_proto_rawDescOnce sync.Once
	file_appsinstalled_proto_rawDescData []byte
)

func file_appsinstalled_proto_rawDescGZIP() []byte {
	file_appsinstalled_proto_rawDescOnce.Do(func() {
		file_appsinstalled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appsinstalled_proto_rawDesc), len(file_appsinstalled_proto_rawDesc)))
	})
	return file_appsinstalled_proto_rawDescData
}

var file_appsinstalled_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_appsinstalled_proto_goTypes = []any{
	(*UserApps)(nil), // 0: UserApps
}
var file_appsinstalled_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_appsinstalled_proto_init() }
func file_appsinstalled_proto_init() {
	if File_appsinstalled_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appsinstalled_proto_rawDesc), len(file_appsinstalled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_appsinstalled_proto_goTypes,
		DependencyIndexes: file_appsinstalled_proto_depIdxs,
		MessageInfos:      file_appsinstalled_proto_msgTypes,
	}.Build()
	File_appsinstalled_proto = out.File
	file_appsinstalled_proto_goTypes = nil
	file_appsinstalled_proto_depIdxs = nil
}
